seq:
	cd sequences; run_all.sh;

build:
	run_all.sh;

clean:
	rm *.aux *.bbl *.blg *.log *.nav *.out *.snm *.toc *.synctex.gz sequences/*.aux sequences/*.bbl sequences/*.blg sequences/*.log sequences/*.nav sequences/*.out sequences/*.snm sequences/*.toc sequences/*.synctex.gz
